require 'rake'
require 'yaml'


desc "Start Local Development"
task :start_local_dev do

	config 						= YAML.load_file('config.yml')
	shopify_themes 		= YAML.load_file('shopify-theme.yml')

	puts ''
	puts "Let's download the Current Live theme files so we're up to date"
	system("git checkout master")
	system("git pull origin master")

	dev_theme_id   		= shopify_themes[:dev_theme]
	dev_theme_name 		= `../shopify-cli.rb theme_name #{dev_theme_id}`
	dev_theme_branch 	= dev_theme_name.downcase

	puts ''
	puts "Create & switch to out development branch"
	system("git checkout -b #{dev_theme_branch}") || system("git checkout #{dev_theme_branch}")

	puts ''
  puts "Switching local environment to the Dev theme..."
  puts system("theme configure #{config[:api_key]} #{config[:password]} biolite-2.myshopify.com #{dev_theme_id}")
  
	puts ''  
  puts "Switch complete, let's upload the Current theme files to the Dev theme so we're in sync"
	puts system("theme upload")

	puts ''  
  puts "Updates complete, turning on 'theme watch', time to start coding..."
	puts 'Current Dev Theme: ' + `../shopify-cli.rb theme_name #{dev_theme_id}`
	puts system("theme watch")
	puts ''  

end

desc "Deploy"
task :deploy do
	shopify_themes = YAML.load_file('shopify-theme.yml')

	github_repo    = shopify_themes[:github_repo]
	master_zip     = "#{github_repo}/archive/master.zip"

	datetime       = DateTime.now.strftime("%F_%H%M%S")
	theme_name     = "Deploy_#{datetime}"

	puts ''  
  puts "Deploying from master..."
	puts system("../shopify-cli.rb create_deploy_theme #{master_zip} #{theme_name}")
	puts ''  
end	

task :describe do
  puts ""
  puts "-- Welcome to the Biolite Shopify Development Theme Environment --"
  puts "This is a collection of simple scripts to help start lcoal development & to deploy"
  puts " Run `rake -T` for all the options"
  puts ""
end

task :default => 'describe'
